Get antenna montioring values in GNSS collector
redhat-partner-solutions/vse-sync-testsuite pull request #49
Opened 2023-06-29 14:43 UTC by nocturnalastro

2023-07-14 15:14 UTC, crwr45 requested changes

2023-07-14 15:14 UTC, crwr45 commented on pkg/collectors/devices/gps_ubx.go
> +	AntBlockID      []int  `json:"antBlockId" fetcherKey:"antBlockId"`
Looking at the rest of this the `Ant` fields should all be in a struct of their own, with one instance per block. That seems to be the natural representation of the data.

2023-07-14 15:40 UTC, nocturnalastro commented on pkg/collectors/devices/gps_ubx.go
> +	AntBlockID      []int  `json:"antBlockId" fetcherKey:"antBlockId"`
I agree :)

2023-07-17 10:53 UTC, crwr45 approved these changes
That's much better, more refined and understandable. lgtm, though we need to consider how it affects the analysers.

2023-07-17 11:13 UTC, nocturnalastro commented
> That's much better, more refined and understandable. lgtm, though we need to consider how it affects the analysers.

Output format is still the same as it is currently as I unpack the values when presenting them [here](https://github.com/redhat-partner-solutions/vse-sync-testsuite/pull/49/files#diff-1a0886da543185f28fc547ad96dd0e84b69178d13556d7be42e050c7d7716f84R48-R51)

2023-07-17 11:13 UTC, merged